package root

// Code generated by github.com/mavolin/corgi v0.5.6. DO NOT EDIT.

import (
	_bytes "bytes"
	_io "io"

	_writeutil "github.com/mavolin/corgi/pkg/writeutil"
)

func RenderNotFound(_w _io.Writer, query string) (err error) {
	var (
		_buf    _bytes.Buffer
		_closed bool
		// in case we never use them
		_ = _buf
		_ = _closed
	)

	_closed = false
	err = _writeutil.Write(_w, "<!doctype html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta content=\"ie=edge\" http-equiv=\"x-ua-compatible\"><link rel=\"stylesheet\" href=\"/static/css/main.css\"><title")
	if err != nil {
		return err
	}
	if !_closed {
		_closed = true
		err = _writeutil.Write(_w, ">")
		if err != nil {
			return err
		}
	}
	err = _writeutil.Write(_w, "Search for ")
	if err != nil {
		return err
	}
	err = _writeutil.WriteHTML(_w, query)
	if err != nil {
		return err
	}
	_closed = false
	err = _writeutil.Write(_w, "</title></head><body")
	if err != nil {
		return err
	}
	if !_closed {
		_closed = true
		err = _writeutil.Write(_w, ">")
		if err != nil {
			return err
		}
	}
	_closed = false
	err = _writeutil.Write(_w, "<div class=\"l-main\"><h1 class=\"l-main__title\">😕 The search yielded no results, try again...</h1><div class=\"l-main__search\"><form action=\"/\" method=\"get\" class=\"c-main-search\"><input type=\"text\" name=\"q\" required aria-label=\"word\" placeholder=\"skribi\"")
	if err != nil {
		return err
	}
	err = _writeutil.WriteAttr(_w, "value", query, false)
	if err != nil {
		return err
	}
	_closed = true
	err = _writeutil.Write(_w, " class=\"c-main-search__input\"><button type=\"submit\" value=\"Search\" class=\"c-main-search__button\"><svg fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\" class=\"c-main-search__button-icon\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z\"></path></svg></button></form></div></div></body>")
	if err != nil {
		return err
	}
	return nil
}
