name: Publish Container
on:
  push:
    # run only against tags
    tags:
      - '*'

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin &&
          docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} . &&
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
